#!/bin/bash
set -e
BASE_PATH=$(cd $(dirname $BASH_SOURCE)/..; pwd)
source $BASE_PATH/hack/message_printing.sh

usage() {
  echo "Usage:"
  echo "run-tests               --- run all the tests"
  echo "run-tests -c            --- create coverage report"
  echo "run-tests -m <Module>   --- only run tests in given module"
  echo "run-tests -v            --- run tests in verbose mode"
  echo "run-tests -h            --- print help menu"
}

setup() {
  info "Starting MongoDB Docker container"
  DOCKER_CONTAINER_ID=$(docker run -d --name test-ice-mongo -p 12222:27017 mongo)
  info "Container is '$DOCKER_CONTAINER_ID'"
}

run_nose() {
  # command
  cmd="nosetests"
  if [ $WITH_COVERAGE -eq 1 ]; then
    cmd=$cmd" --with-coverage"
    cmd=$cmd" --cover-package ice"
    cmd=$cmd" --cover-html"
    cmd=$cmd" --cover-erase"
    cmd=$cmd" --cover-html-dir coveragereport"
  fi
  cmd=$cmd" -v"
  [ "$MODULE" != "" ] && cmd=$cmd" $MODULE"

  # envars
  export TEST_ICE_MONGO_PORT=12222
  [ $DEBUG -eq 1 ] && export TEST_ICE_DEBUG=1

  info "About to run '$cmd'"

  # run tests but don't blow up
  info "--------- Nose output START ---------"
  set +e
  eval $cmd
  TESTS_EXIT_CODE=$?
  set -e
  info "--------- Nose output END ---------"

  info "Nose exited with code $TESTS_EXIT_CODE"
}

teardown() {
  info "Removing MongoDB Docker container"
  docker rm -f test-ice-mongo > /dev/null
  info "The Docker container got cleaned up!"
}

DEBUG=0
MODULE=""
WITH_COVERAGE=0
while getopts "m:cvh" OPTION
do
  case $OPTION in
    m)
      MODULE=$OPTARG
      ;;
    c)
      WITH_COVERAGE=1
      ;;
    v)
      DEBUG=1
      ;;
    h)
      usage
      exit
      ;;
    *)
      usage
      exit
      ;;
  esac
done

debug "run_integration=$RUN_INTEGRATION"
debug "module='$MODULE'"
debug "with_coverage=$WITH_COVERAGE"
debug "verbose=$DEBUG"

# some action...
setup
run_nose
teardown

exit $TESTS_EXIT_CODE
